version: "3.9"
services:
  python:
    build: .
    ports:
      - "80:80"
  mongodb:
    image: mongo 
    ports:
     - "27017:27017"
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=1234